# Generated by Django 4.2.3 on 2023-07-23 10:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todoapps", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="status",
            field=models.IntegerField(
                choices=[(0, "未完了"), (1, "完了")], verbose_name="ステータス"
            ),
        ),
    ]
